apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStream
metadata:
  name: pds-sample-w-imagerepo
  ownerReferences:
  - apiVersion: projctl.konflux.dev/v1beta1
    kind: Project
    name: project-sample
spec:
  project: project-sample
  template:
    name: pdst-sample-w-imagerepo
    values:
    - name: version
      value: "2.2.0"
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: "cool-app-2-2-0"
  ownerReferences:
  - apiVersion: "projctl.konflux.dev/v1beta1"
    kind: "ProjectDevelopmentStream"
    name: "pds-sample-w-imagerepo"
spec:
  displayName: "Cool App 2.2.0"
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: "cool-comp1-2-2-0"
  ownerReferences:
  - apiVersion: "appstudio.redhat.com/v1alpha1"
    kind: "Application"
    name: "cool-app-2-2-0"
spec:
  application: "cool-app-2-2-0"
  componentName: "cool-comp1-2-2-0"
  source:
    git:
      context: "./"
      dockerfileUrl: "Dockerfile"
      revision: "2.2.0"
      url: git@github.com:example/comp1.git
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  name: "cool-comp1-repo-2-2-0"
  labels:
    appstudio.redhat.com/component: "cool-comp1-2-2-0"
    appstudio.redhat.com/application: "cool-app-2-2-0"
  ownerReferences:
  - apiVersion: "appstudio.redhat.com/v1alpha1"
    kind: "Component"
    name: "cool-comp1-2-2-0"
spec:
  image:
    visibility: public
    name: coolorg/cool-app-2-2-0/cool-comp1-2-2-0
  credentials:
    verify-linking: true
